spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
management:
  endpoint:
    health:
      show-details: never
springdoc:
  api-docs:
    enabled: false
