name: CI

on:
  push:
    branches: [ develop ]
  pull-request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker build
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for containers to be ready
        run: sleep 15

      - name: Run tests inside app container
        run: docker compose exec -T app ./mvnw clean test

      - name: Shutdown containers
        if: always()
        run: docker compose down -v